apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: demo-app
spec:
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 5000 # Service port (how other services access it)
      targetPort: 5000 # Container port (what the app listens on)
  type: ClusterIP # Internal service, only accessible within the cluster
